def notify(status) {
    wrap([$class: 'BuildUser']) {
        echo "Full Name: $BUILD_USER"
        echo "User Id: $BUILD_USER_ID"
        emailext (
        subject: "${status}: Job ${env.JOB_NAME} ([${env.BUILD_NUMBER})",
        body: """
        Check console output at <a href="${env.BUILD_URL}">${env.JOB_NAME} (${env.BUILD_NUMBER})</a>""",
        to: "anu_wilson@apple.com",
        from: 'jenkins@company.com')
               }
}
pipeline {
    agent { label 'master' }
    environment {
       color = "blue"
   }
    stages {
        stage('build') {
            steps {
                echo "Hello World!"
                sh "echo Hello from the shell"
                sh "hostname"
                sh "uptime"
               wrap([$class: 'BuildUser']) {
                   echo "Full Name: $BUILD_USER"
                   echo "User Id: $BUILD_USER_ID"
                   echo "Mail Id: $BUILD_USER_EMAIL"
                   echo "Build URL : ${env.BUILD_URL}"
                   echo "Job Name : ${env.JOB_NAME}"
                   echo "Build Number : ${env.BUILD_NUMBER}"
                steps {
               sh "printenv | sort"
            }
               }
            }
        }
    }
}
